config/routes.rb
Rails.application.routes.draw do
  resources :jogos
  get '/jogos/show/all/', to: 'jogos#get_all'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/jogo.rb
class Jogo < ApplicationRecord
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/jogos_controller.rb
class JogosController < ApplicationController
  before_action :set_jogo, only: [:show, :edit, :update, :destroy]

  # GET /jogos
  # GET /jogos.json
  def index
    @jogos = Jogo.all
  end

  # GET /jogos/1
  # GET /jogos/1.json
  def show
    @jogo = Jogo.find(params[:id])
  end

  # GET /jogos/new
  def new
    @jogo = Jogo.new
    arrayNumbers = 6.times.map{ Random.rand(1...60) }
    @jogo.one = arrayNumbers[0]
    @jogo.two = arrayNumbers[1]
    @jogo.three = arrayNumbers[2]
    @jogo.four = arrayNumbers[3]
    @jogo.five = arrayNumbers[4]
    @jogo.six = arrayNumbers[5]
    @jogo.save
  end

  # GET /jogos/1/edit
  def edit
  end

  # POST /jogos
  # POST /jogos.json
  def create
    @jogo = Jogo.new(jogo_params)

    respond_to do |format|
      if @jogo.save
        format.html { redirect_to @jogo, notice: 'Jogo was successfully created.' }
        format.json { render :show, status: :created, location: @jogo }
      else
        format.html { render :new }
        format.json { render json: @jogo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jogos/1
  # PATCH/PUT /jogos/1.json
  def update
    respond_to do |format|
      if @jogo.update(jogo_params)
        format.html { redirect_to @jogo, notice: 'Jogo was successfully updated.' }
        format.json { render :show, status: :ok, location: @jogo }
      else
        format.html { render :edit }
        format.json { render json: @jogo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jogos/1
  # DELETE /jogos/1.json
  def destroy
    @jogo.destroy
    respond_to do |format|
      format.html { redirect_to jogos_url, notice: 'Jogo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /jogos/all
  def get_all
    @jogos = Jogo.all
    render "jogos/show_all"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jogo
      @jogo = Jogo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def jogo_params
      params.fetch(:jogo, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jogos_helper.rb
module JogosHelper
end

app/views/jogos/_form.html.erb
<%= form_with(model: jogo, local: true) do |form| %>
  <% if jogo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(jogo.errors.count, "error") %> prohibited this jogo from being saved:</h2>

      <ul>
        <% jogo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jogos/edit.html.erb
<h1>Editing Jogo</h1>

<%= render 'form', jogo: @jogo %>

<%= link_to 'Show', @jogo %> |
<%= link_to 'Back', jogos_path %>

app/views/jogos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jogos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jogos.each do |jogo| %>
      <tr>
        <td><%= link_to 'Show', jogo %></td>
        <td><%= link_to 'Edit', edit_jogo_path(jogo) %></td>
        <td><%= link_to 'Destroy', jogo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Jogo', new_jogo_path %>

app/views/jogos/new.html.erb
<h1>New Jogo</h1>

<%= render 'form', jogo: @jogo %>

<%= link_to 'Back', jogos_path %>

app/views/jogos/show.html.erb
<p id="notice"><%= notice %></p>

<p><%= @jogo.id %></p>
<p><%= @jogo.one %></p>
<p><%= @jogo.two %></p>
<p><%= @jogo.three %></p>
<p><%= @jogo.four %></p>
<p><%= @jogo.five %></p>
<p><%= @jogo.six %></p>

<%= link_to 'Edit', edit_jogo_path(@jogo) %> |
<%= link_to 'Back', jogos_path %>

app/views/jogos/show_all.html.erb
<p id="notice"><%= notice %></p>

<% @jogos.each do |jogo| %>
    <div>
        <p> Jogo: <%= jogo.id %></p>
        <p><%= jogo.one %></p>
        <p><%= jogo.two %></p>  
        <p><%= jogo.three %></p>
        <p><%= jogo.four %></p>
        <p><%= jogo.five %></p>
        <p><%= jogo.six %></p>
        <br/>
    </div>
<% end %>


<%= link_to 'Back', jogos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Megavirada</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>